//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Mekan.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MekanProjeEntities1 : DbContext
    {
        public MekanProjeEntities1()
            : base("name=MekanProjeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
        public virtual DbSet<TBLHAKKIMIZDA> TBLHAKKIMIZDA { get; set; }
        public virtual DbSet<TBLILETISIM> TBLILETISIM { get; set; }
        public virtual DbSet<TBLMEKAN> TBLMEKAN { get; set; }
        public virtual DbSet<TBLSEHIR> TBLSEHIR { get; set; }
        public virtual DbSet<TBLYORUM> TBLYORUM { get; set; }
        public virtual DbSet<TBLMESAJ> TBLMESAJ { get; set; }
    }
}
