//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Mekan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMEKAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMEKAN()
        {
            this.TBLYORUM = new HashSet<TBLYORUM>();
        }
    
        public int MEKANID { get; set; }
        public string MEKANRESIM { get; set; }
        public string MEKANBASLIK { get; set; }
        public string MEKANBILGI { get; set; }
        public Nullable<byte> MEKANSEHIR { get; set; }
    
        public virtual TBLSEHIR TBLSEHIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLYORUM> TBLYORUM { get; set; }
    }
}
