//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Mekan.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSEHIR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLSEHIR()
        {
            this.TBLMEKAN = new HashSet<TBLMEKAN>();
        }
    
        public byte SEHIRID { get; set; }
        public string SEHIRAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMEKAN> TBLMEKAN { get; set; }
    }
}
